:github-address: https://github.com/hazelcast-guides/hibernate-jcache
:templates-url: templates:ROOT:page$/
:plugin-gh-address: https://github.com/hazelcast/hazelcast-hibernate

= JCache SPI for using Hazelcast as L2C for Hibernate

Configuration details to use JCache SPI for Hibernate Second Level Cache backed by Hazelcast IMDG.

You can find the code samples for entity cache, collection cache, and query cache use cases {github-address}[here.]

== What You’ll Learn

You will be able to use Hibernate Second Level Cache using JCache SPI rather than `Hazelcast-hibernate` plugin.

This is an alternative approach of using {plugin-gh-address}[Hazelcast-hibernate] plugin to use Hazelcast as the caching provider for Hibernate. Note that the local region caches supported by the plugin are not available here, unlike plugin - which stores query results locally. This approach supports query results to be stored in a distributed map.

=== About Jcache

https://www.javadoc.io/doc/javax.cache/cache-api/1.1.1[JCache (JSR 107)] is a standard caching API for Java.

It provides an API for applications to be able to create and work with an in-memory cache of objects. Hibernate has
started to support Jcache implementations for L2C with version 5.2. Using only a `CachingProvider` implementation,
L2C can be used for `SessionFactory` objects in Hibernate.

== Prerequisites

- JDK 8+
- Apache Maven 3.2+

== Required Dependencies

In `pom.xml`, include `hibernate-jcache` dependency having the same version with `hibernate-core` in your project:

[source, xml]
----
<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-jcache</artifactId>
    <version>${hibernate-core.version}</version>
</dependency>
----

Make sure to include, the `hazelcast` dependency as well:

[source, xml]
----
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast</artifactId>
    <version>${hazelcast.version}</version>
</dependency>
----

== Configuring Hibernate JCache Region Factory

Now tell Hibernate to use JCache region factory. For Hibernate 5.2.x:
[source, xml]
----
<property name="hibernate.cache.region.factory_class">
   org.hibernate.cache.jcache.JCacheRegionFactory
</property>
----


For Hibernate 5.3.0 and higher:
[source, xml]
----
<property name="hibernate.cache.region.factory_class">
   jcache
</property>
----

== Confiuguring Cache Provider

You can use either Hazelcast Embedded or Client/Server mode as the cache provider.

****
`CLIENT`: You can connect to an existing Hazelcast cluster and store the cache data there. Then you can scale the cluster
up or down independently from your app. Data resides in L2C can be available even a SessionFactory is closed
, or application is shut down. So this makes L2C available across SessionFactories and Hibernate applications.

`EMBEDDED`: A new Hazelcast instance is created along with your application. This instance cannot be scaled up or
down unless you run or shutdown another Hibernate application with the same server config. The latency of communicating to
Hazelcast Cluster will be less than the client mode.

- You can learn more about the differences between client and embedded topologies https://docs.hazelcast.org/docs/latest/manual/html-single/#hazelcast-topology[here.]
****


Now configure the provider in Hibernate configuration. To use native client:

[source, xml]
----
<property name="hibernate.javax.cache.provider">
   com.hazelcast.client.cache.impl.HazelcastClientCachingProvider
</property>
<property name="hibernate.javax.cache.uri">
   hazelcast-client.xml
</property>
----

To use embedded Hazelcast instance:

[source, xml]
----
<property name="hibernate.javax.cache.provider">
   com.hazelcast.cache.impl.HazelcastServerCachingProvider
</property>
<property name="hibernate.javax.cache.uri">
   hazelcast.xml
</property>
----

You can configure your Hazelcast instances over `hazelcast.xml` or `hazelcast-client.xml`.


== Cache Configuration

Configure the cache via `hazelcast.xml`, `<cache>` part:

[source, xml]
----
<cache name="custom.cache.region.name">
    <statistics-enabled>true</statistics-enabled>
    <management-enabled>true</management-enabled>
    <eviction size="10000" max-size-policy="ENTRY_COUNT" eviction-policy="LRU" />
</cache>
----

NOTE: To track the cache statistics on Hazelcast Management Center, you have to enable the statistics
(disabled by default) for the cache configuration of the Hazelcast instance.

NOTE: If client mode is used, cache configurations must be set on the server configuration (`hazelcast.xml`), not on the client-side (`hazelcast-client.xml`).

TIP: If you do not define a specific region name, the default cache configuration is going to be
used for this region. Hence it will not be visible on Hazelcast Management Center. To apply
a config to all regions, you can use a wildcard for `name` property (e.g., `name="*"`).

For other cache configuration properties, see cache configuration section on the documentation
https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#icache-configuration[here].
Eviction size and policy properties might be useful for this case.


== Summary

You have configured your Hibernate app to use second-level cache using JCache SPI backed by Hazelcast. Now you can see Hibernate storing fetched objects from the database in the second-level cache and serving them if available. You can find the code samples for entity cache, collection cache, and query cache use cases {github-address}[here.]


== See Also

- {plugin-gh-address}[Hazelcast Hibernate Second Level Cache Plugin]
- xref:springboot-hibernate:ROOT:index.adoc[Hazelcast L2C for Hibernate in SpringBoot]
- xref:hazelcast-embedded-springboot:ROOT:index.adoc[Hazelcast in SpringBoot]


